### PR TITLE
Setting the setup script to exit on completion

### PR DESCRIPTION
**Pull request by gavinhughpalmer**
- [x] I’ve added tests to confirm my change works.
- [x] (If changing formatting output/API or CLI) I’ve added my changes to the `CHANGELOG.md` file in the `Unreleased` section.
- [x] I’ve read the [contributing guidelines](https://github.com/dangmai/prettier-plugin-apex/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gavinhughpalmer** [comment]
As the start-apex-server command doesn't currently have any tests surrounding it I have not added any additional coverage. Let me know if you have any concerns with the change

**Comment by dangmai** [comment]
Hi @gavinhughpalmer, thanks for the PR and sorry for the long turnaround time on this, I had some other stuff in real life to take care of so didn't have time the past couple of weeks to review it.

I am a little bit confused by this PR though, if we exit the process right after calling `setup()`, the HTTP server is no longer running and Prettier Apex won't be able to use that server anymore. This is because NodeJS `spawn` does not daemonize the process by default, so exiting the main process will also exit the child process. Am I missing something here?

**Comment by gavinhughpalmer** [comment]
Hi @dangmai,

Thanks for getting back on the PR. 

In my testing this has worked and we are able to reuse the server after exiting from the command. I understand what you mean about the spawn not daemonizing the process, but I don't think it needs to in this instance, as the command has finished executing (and the language server is then running) by the time the process executes. 

The issue I was originally having was I was trying to run prettier in an automated context, then when using the language server if I executed `start-apex-server` the command would of course not exit and leave the process hanging. The wor around I have used is to daemonizing the command within bash, but of course, this means the next command executed runs before the server has setup. I got around this by adding in a wait command.

I hope this makes sense, I am happy to make some additions if you think I am missing something.

**Comment by dangmai** [comment]
Thank you for the context. In CI/CD context the easiest way to handle that is something like this:

```bash
nohup start-apex-server &
npx wait-on http://localhost:2117/api/ast/
prettier --check 'project/**/*.{trigger,cls}' --apex-standalone-parser built-in 
stop-apex-server
```

Which basically does what you describe, but a bit more elegantly because you don't need to sleep for a specific amount of time.

For the PR though, I actually cannot get the server to continue running as you have it currently (i.e. as soon as the process exits the language server is no longer running). If you don't mind can you post your pipeline here? I'm curious to know how it works in your situation, unless you have made other changes to the code base somewhere else (maybe with `detached: true` when calling `spawn`).

**Comment by gavinhughpalmer** [comment]
Thanks for the tip on the CI context that looks like it would solve the
requirement there.

I have made no other changes, I wonder if it is to do with the machine I am
working on. I have run a couple of tests with different docker images (one
with the salesforcedx and one with the node image), on the salesforcedx one
I see the same behaviour as on my machine (a macbook), but the node image,
will hold the process open regardless, which suggests to me that line never
gets hit so something internally is holding the process open.

I wonder if the best solution is to do as you have suggested and include
the detached: true which should allow this to work regardless of OS.

**Comment by dangmai** [comment]
I will put those commands into the README so that everyone can have guidance on how to do CI/CD with Prettier Apex.

When it comes to the process spawning, I don't think detaching it is the way to go. In my mind it's too easy to forget that you have run that command on your dev machine, and then you'll have an orphan process that listens to HTTP requests which is a little bit scary. I'd prefer that users use external tooling (like `nohup` in the *nix world) to do that themselves if that is something they want to achieve.

I'll close this PR since it's not working at the current state, feel free to add more discussion here or open a new issue.

Thank you for suggestions and ideas!

**Pull request closed without merging**
