### PR TITLE
Add built-in-autolaunched

### PR DESCRIPTION
**Pull request by nawforce**
This adds a new option 'built-in-autolaunched' that will automatically start a local server if it is not already running. It detects if a server is not running by simply trying to use it and catching the error when it is not available. 

As the server may take a few seconds to be able to respond to requests it has fallback handling to use ‘spawn’ to use the standalone JVM version even when autolaunch has been selected. This means that the first few requests may still be handled in the slow way but subsequent requests will be handled by the server.

- [*] I’ve added tests to confirm my change works.
- [x] (If changing formatting output/API or CLI) I’ve added my changes to the `CHANGELOG.md` file in the `Unreleased` section.
- [x] I’ve read the [contributing guidelines](https://github.com/dangmai/prettier-plugin-apex/blob/master/CONTRIBUTING.md).

* I looked at the existing test setup but could not find existing tests for CLI behaviour to extends so thought best PR as is and see what you think.

### CODE REVIEW

**Comment by dangmai** [comment]
Hi @nawforce, thank you for the PR and many apologies for my really late response - there were some real life issues I had to deal with the past week and I haven't had time to work on Prettier Apex.

I am a bit torn about this PR. In general I prefer not to redo work that can be done by external tooling, and a command as suggested in https://github.com/dangmai/prettier-plugin-apex/issues/204 uses *nix tooling really well to cover a very similar use case to this PR. Here are a few cons that I can think of for this approach:

- The first few requests cannot take advantage of the http server anyway, because there's no way to wait for the server to be up.

- The error behavior here is implicit, similar to #204 - let's say someone creates a CI/CD process that uses this option to launch the server and it worked initially. Later on maybe something changes in the pipeline (let's say they spin up a completely different HTTP server that uses the same port), Prettier Apex HTTP server will fail to launch and yet the code will continue to be formatted (just an order of magnitude slower). This is an issue for people who pays by the minute for their CI/CD pipeline - no error has been thrown and yet they have to pay ~10 times more for their pipeline. 

The pros for this approach is that it is cross platform, but one could argue that we can document the commands to spin up the HTTP server in README for both Linux and Windows.

Can you go into more detail about your use case for this flag?

**Comment by nawforce** [comment]
Hi @dangmai, no problem at all, we all have other lives to live ;-) 

So this is literally really just about getting the performance benefit without having to manually start a server. When we talked about this last time I think we thought having a shared server for our developers would make more sense but I rather failed to get that passed our DevOps/IT so this is my alternative approach.

Understand if you think this does not fit, I could just do a wrapper/alternative module for them for now that does pretty much this. I was kind of thinking about that anyway as I have an optimised JS parser these days that is another option I should work on.

**Comment by drubin** [comment]
I was going to start the same PR. This manually starting and stopping the server is super annoying and even worse in a CI  env.

I was   actually looking for a hook to start the HTTP server before the parsing happens. Maybe using `yargs` hooks? is this possible? (not 100% familiar with prettier plugin system but it seems like its standard yargs?)

**Comment by drubin** [comment]
hi @dangmai I think I may have found a nice workaround for CI envs.

Most CI env's GitLab and GitHub support `services`. If you publish a docker image of this and or 
https://github.com/dangmai/apex-ast-serializer  these can be used to configure the service.

Example 

```yaml 
lint:
  stage: lint
  services:
  - name: dangmai/apex-ast-serializer:1.7.0
    alias: apex-ast-serializer
  before_script:
  - npm install
  script:
  - prettier  --apex-standalone-parser built-in --debug-check src/**/*.{trigger,cls}
```

It would be nice this image allowed configuration with env variables so this could be passed in.

Currently, I am doing a little bit o a hack by using the `npm` package to start the java server (but this increases the images size) but it works.

Maybe this helps others, but also solves these meta problems (btw services normally check the port is up before running scripts)

**Pull request closed without merging**
